# Generated by Django 4.1.2 on 2022-11-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID Employee')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('roles', models.CharField(blank=True, max_length=100, null=True, verbose_name='Roles')),
                ('start_date_report', models.DateField(verbose_name='Start Date Report')),
                ('end_date_report', models.DateField(verbose_name='End Date Report')),
                ('total_hours', models.FloatField(blank=True, null=True, verbose_name='Total Hours')),
                ('hours_work_in_vacations', models.FloatField(blank=True, null=True, verbose_name='Holiday working hours')),
                ('hours_work_in_sick_leave', models.FloatField(blank=True, null=True, verbose_name='Working hours in sickness')),
                ('time_in_vacations', models.TextField(blank=True, null=True, verbose_name='Vacation time')),
                ('time_in_sick_leave', models.TextField(blank=True, null=True, verbose_name='Time in sickness')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created report')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated report')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'get_latest_by': 'created_at',
            },
        ),
    ]
